//
// Created by Christos Tsakostas on 08/11/2023.
//

#ifndef CXX_DETECTVOICEACTIVITYDOMAINSERVICEWITHOPUSVAD_H
#define CXX_DETECTVOICEACTIVITYDOMAINSERVICEWITHOPUSVAD_H


class DetectVoiceActivityDomainServiceWithOpusVad {

};


#endif //CXX_DETECTVOICEACTIVITYDOMAINSERVICEWITHOPUSVAD_H
